#!/bin/bash

# description and help
function show_help() {
    cat > /dev/stdout << END
USAGE: ${0##*/} [-h] -s id -d subjects/dir -o output

DESCRIPTION:
${0##*/} extract sub-cortical ROIs from Freesurfer's segmentation. It can use
the labels generated by fs_cortical_rois.sh (using the -c argument).

REQUIRED ARGS:
-s: subject id
-d: subjects directory (SUBJECTS_DIR)
-o: output dir

DEPENDENCIES:

The awk file subcortical_masks_script.awk in ${0%/*}

END
}

function show_error_required() {
    cat > /dev/stderr << END
ERROR: missing argument/s. 

Actual values:

-d ${SUBJECTS_DIR}
-s ${SUBJ}
-o ${OUTPUT_DIR}

Usage:

END
show_help
}

# reset vars
# note: SUBJECTS_DIR is necessary because using only the --sd flag does
# not work for all commands
SUBJECTS_DIR=""
OUTPUT_DIR=""
SUBJ=""
CORTICAL_DIR=""
AWK_SCRIPT=${0%/*}/subcortical_masks_script.awk

# Parse args
while getopts "h?:s:o:d:" opt; do
    case "${opt}" in
        h|\?)
            show_help
            exit 0;;
        s)
            SUBJ=${OPTARG};;
        o)
            OUTPUT_DIR=${OPTARG};;
        d)
            SUBJECTS_DIR=${OPTARG};;
        c)
            CORTICAL_DIR=${OPTARG};;
    esac
done

if [[ ${SUBJ} = "" || ${SUBJECTS_DIR} = "" || ${OUTPUT_DIR} = "" ]]; then
    show_error_required
    exit 1
fi

if [[ ! -f ${AWK_SCRIPT} ]]; then
    echo !!! Error: ${AWK_SCRIPT} not found
    echo !!! Exiting
    exit 1
fi

SINK_DIR=${SUBJECTS_DIR}/${SUBJ}/${OUTPUT_DIR}
mkdir -p ${SINK_DIR}

OUT_SCRIPT=${SINK_DIR}/subcortical_extract_masks.sh

pushd ${SINK_DIR} &> /dev/null
echo +++ Move segmentation results to original input -- raw -- space

mri_label2vol --seg ${SUBJECTS_DIR}/${SUBJ}/mri/aseg.mgz\
    --temp ${SUBJECTS_DIR}/${SUBJ}/mri/rawavg.mgz\
    --o ${SINK_DIR}/aseg_in_rawavg.nii.gz\
    --regheader ${SUBJECTS_DIR}/${SUBJ}/mri/aseg.mgz

echo +++ Write out aseg.sum
# could try to use stats/aseg.stats but will need to filter out regions
# that are not really in the volume (0 mm^3) and the file format is
# slightly more complicated; better use the sum file
mri_segstats --seg ${SUBJECTS_DIR}/${SUBJ}/mri/aseg.mgz \
    --excludeid 0 --ctab ${FREESURFER_HOME}/FreeSurferColorLUT.txt \
    --sum ${SINK_DIR}/aseg.sum

echo +++ Write out script to make the masks
gawk -f ${AWK_SCRIPT} -v niftifile=${SINK_DIR}/aseg_in_rawavg.nii.gz \
    ${SINK_DIR}/aseg.sum > ${OUT_SCRIPT}

echo +++ Running ${OUT_SCRIPT}
chmod +x ${OUT_SCRIPT}
${OUT_SCRIPT}
popd &> /dev/null
echo +++ Done
echo +++ Masks should be in ${SINK_DIR}
echo +++ Bye
exit 0
