#!/bin/bash

# description and help
function show_help() {
    cat > /dev/stdout << END
USAGE: ${0##*/} [-h] -s id -d subjects/dir -o output

DESCRIPTION:
${0##*/} extract sub-cortical ROIs from Freesurfer's segmentation. It can use
the labels generated by fs_cortical_rois.sh (using the -c argument).

REQUIRED ARGS:
-s: subject id
-d: subjects directory (SUBJECTS_DIR)
-o: output dir

END
}

function show_error_required() {
    cat > /dev/stderr << END
ERROR: missing argument/s. 

Actual values:

-d ${SUBJECTS_DIR}
-s ${SUBJ}
-o ${OUTPUT_DIR}

Usage:

END
show_help
}

# reset vars
# note: SUBJECTS_DIR is necessary because using only the --sd flag does
# not work for all commands
SUBJECTS_DIR=""
OUTPUT_DIR=""
SUBJ=""
CORTICAL_DIR=""

# Parse args
while getopts "h?:s:o:d:" opt; do
    case "${opt}" in
        h|\?)
            show_help
            exit 0;;
        s)
            SUBJ=${OPTARG};;
        o)
            OUTPUT_DIR=${OPTARG};;
        d)
            SUBJECTS_DIR=${OPTARG};;
        c)
            CORTICAL_DIR=${OPTARG};;
    esac
done

if [[ ${SUBJ} = "" || ${SUBJECTS_DIR} = "" || ${OUTPUT_DIR} = "" ]]; then
    show_error_required
    exit 1
fi

SINK_DIR=${SUBJECTS_DIR}/${SUBJ}/${OUTPUT_DIR}
mkdir -p ${SINK_DIR}

echo +++ Move segmentation results to original input -- raw -- space

mri_label2vol --seg ${SUBJECTS_DIR}/${SUBJ}/mri/aseg.mgz\
    --temp ${SUBJECTS_DIR}/${SUBJ}/mri/rawavg.mgz\
    --o ${SINK_DIR}/aseg_in_rawavg.nii.gz\
    --regheader ${SUBJECTS_DIR}/${SUBJ}/mri/aseg.mgz

echo +++ Creating amygdala mask

# amygdala 18, 54
# Values at FSTutorial/AnatomicalROI/FreeSurferColorLUT
fslmaths ${SINK_DIR}/aseg_in_rawavg.nii.gz -thr 18 -uthr 18\
    ${SINK_DIR}/lh_amygdala.nii.gz
fslmaths ${SINK_DIR}/aseg_in_rawavg.nii.gz -thr 54 -uthr 54\
    ${SINK_DIR}/rh_amygdala.nii.gz

echo +++ Creating thalamus mask

# thalamus 10, 49
fslmaths ${SINK_DIR}/aseg_in_rawavg.nii.gz -thr 10 -uthr 10\
    ${SINK_DIR}/lh_thalamus.nii.gz
fslmaths ${SINK_DIR}/aseg_in_rawavg.nii.gz -thr 49 -uthr 49\
    ${SINK_DIR}/rh_thalamus.nii.gz

# example script, for now, to show how to extract subcortical regions
# for d in $(ls ${1}); do
#     mri_annotation2label --subject $d --hemi lh --outdir $(pwd)/${d}/label
#     mri_annotation2label --subject $d --hemi rh --outdir $(pwd)/${d}/label
#     # generate precuneus masks
#     mri_label2vol --label ${d}/label/lh.precuneus.label --temp ${d}/mri/rawavg.mgz --o ${d}/label/lh_precuneus.nii.gz --regheader ${d}/mri/aseg.mgz 
#     mri_label2vol --label ${d}/label/rh.precuneus.label --temp ${d}/mri/rawavg.mgz --o ${d}/label/rh_precuneus.nii.gz --regheader ${d}/mri/aseg.mgz 
#     # move the results of the segmentation to raw (original input) average space
#     # before we generate the subcortical volumetric masks
#     mri_label2vol --seg ${d}/mri/aseg.mgz --temp ${d}/mri/rawavg.mgz --o ${d}/label/aseg_in_rawavg.nii.gz --regheader ${d}/mri/aseg.mgz    
#     # generate amygdala mask, labels 18 right and 54 left (could be other/s
#     # structures). Values at FSTutorial/AnatomicalROI/FreeSurferColorLUT
#     fslmaths ${d}/label/aseg_in_rawavg.nii.gz -thr 18 -uthr 18 -bin ${d}/label/lh_amygdala.nii.gz
#     fslmaths ${d}/label/aseg_in_rawavg.nii.gz -thr 54 -uthr 54 -bin ${d}/label/rh_amygdala.nii.gz
# done

